"""baseline: mevcut sema

Revision ID: 5d2a9a282ea1
Revises: 
Create Date: 2026-08-21 14:50:38.992746

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '5d2a9a282ea1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BlacklistedTokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime().with_variant(mssql.DATETIME2(precision=7), 'mssql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_BlacklistedTokens_id'), 'BlacklistedTokens', ['id'], unique=False)
    op.create_index(op.f('ix_BlacklistedTokens_jti'), 'BlacklistedTokens', ['jti'], unique=True)
    op.create_table('Databases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('servername', sa.String(length=100), nullable=False),
    sa.Column('database_name', sa.String(length=100), nullable=False),
    sa.Column('technology', sa.String(length=100), nullable=False),
    sa.Column('db_username', sa.String(length=100), nullable=True),
    # EncryptedText's DB-level type is its `impl` (plain Text) — encryption
    # happens in the application layer, not the schema. Migrations describe
    # the schema, so app model classes are deliberately not imported here.
    sa.Column('db_password', sa.Text(), nullable=True),
    sa.Column('uuid', sa.String(length=36).with_variant(mssql.UNIQUEIDENTIFIER(), 'mssql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servername', 'database_name', name='uq_server_database')
    )
    op.create_index(op.f('ix_Databases_id'), 'Databases', ['id'], unique=False)
    op.create_index(op.f('ix_Databases_uuid'), 'Databases', ['uuid'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.create_table('ActionLogging',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('query_date', sa.DateTime().with_variant(mssql.DATETIME2(precision=7), 'mssql'), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('machine_name', sa.String(length=50), nullable=False),
    sa.Column('ExecutionDurationMS', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('isSuccessfull', sa.Boolean(), nullable=True),
    sa.Column('ErrorMessage', sa.Text().with_variant(sa.TEXT(), 'mssql'), nullable=True),
    sa.Column('applied_masking_rules', sa.Text().with_variant(sa.TEXT(), 'mssql'), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('approved_execution', sa.Boolean(), nullable=True),
    sa.Column('approval_status', sa.Enum('AUTO_APPROVED', 'PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_by_slack_id', sa.String(length=20), nullable=True),
    sa.Column('approved_at', sa.DateTime().with_variant(mssql.DATETIME2(precision=7), 'mssql'), nullable=True),
    sa.Column('database_id', sa.Integer(), nullable=True),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['Databases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ActionLogging_approval_status'), 'ActionLogging', ['approval_status'], unique=False)
    op.create_index(op.f('ix_ActionLogging_database_id'), 'ActionLogging', ['database_id'], unique=False)
    op.create_index(op.f('ix_ActionLogging_id'), 'ActionLogging', ['id'], unique=False)
    op.create_index(op.f('ix_ActionLogging_machine_name'), 'ActionLogging', ['machine_name'], unique=False)
    op.create_index(op.f('ix_ActionLogging_trace_id'), 'ActionLogging', ['trace_id'], unique=False)
    op.create_index(op.f('ix_ActionLogging_user_id'), 'ActionLogging', ['user_id'], unique=False)
    op.create_index(op.f('ix_ActionLogging_username'), 'ActionLogging', ['username'], unique=False)
    op.create_table('LoginLogging',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_date', sa.DateTime().with_variant(mssql.DATETIME2(precision=7), 'mssql'), nullable=False),
    sa.Column('client_ip', sa.String(), nullable=False),
    sa.Column('logout_date', sa.DateTime().with_variant(mssql.DATETIME2(precision=7), 'mssql'), nullable=True),
    sa.Column('login_duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LoginLogging_id'), 'LoginLogging', ['id'], unique=False)
    op.create_table('MaskingRules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('masking_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['Databases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MaskingRules_id'), 'MaskingRules', ['id'], unique=False)
    op.create_table('QueryData',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('servername', sa.String(length=50), nullable=True),
    sa.Column('database_name', sa.String(length=50), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('uuid', sa.String(length=36).with_variant(mssql.UNIQUEIDENTIFIER(), 'mssql'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_QueryData_id'), 'QueryData', ['id'], unique=False)
    op.create_index(op.f('ix_QueryData_uuid'), 'QueryData', ['uuid'], unique=False)
    op.create_table('UserDatabaseAssociation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['Databases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'database_id')
    )
    op.create_table('Workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('show_results', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['QueryData.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id')
    )
    op.create_index(op.f('ix_Workspaces_id'), 'Workspaces', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Workspaces_id'), table_name='Workspaces')
    op.drop_table('Workspaces')
    op.drop_table('UserDatabaseAssociation')
    op.drop_index(op.f('ix_QueryData_uuid'), table_name='QueryData')
    op.drop_index(op.f('ix_QueryData_id'), table_name='QueryData')
    op.drop_table('QueryData')
    op.drop_index(op.f('ix_MaskingRules_id'), table_name='MaskingRules')
    op.drop_table('MaskingRules')
    op.drop_index(op.f('ix_LoginLogging_id'), table_name='LoginLogging')
    op.drop_table('LoginLogging')
    op.drop_index(op.f('ix_ActionLogging_username'), table_name='ActionLogging')
    op.drop_index(op.f('ix_ActionLogging_user_id'), table_name='ActionLogging')
    op.drop_index(op.f('ix_ActionLogging_trace_id'), table_name='ActionLogging')
    op.drop_index(op.f('ix_ActionLogging_machine_name'), table_name='ActionLogging')
    op.drop_index(op.f('ix_ActionLogging_id'), table_name='ActionLogging')
    op.drop_index(op.f('ix_ActionLogging_database_id'), table_name='ActionLogging')
    op.drop_index(op.f('ix_ActionLogging_approval_status'), table_name='ActionLogging')
    op.drop_table('ActionLogging')
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Databases_uuid'), table_name='Databases')
    op.drop_index(op.f('ix_Databases_id'), table_name='Databases')
    op.drop_table('Databases')
    op.drop_index(op.f('ix_BlacklistedTokens_jti'), table_name='BlacklistedTokens')
    op.drop_index(op.f('ix_BlacklistedTokens_id'), table_name='BlacklistedTokens')
    op.drop_table('BlacklistedTokens')
    # ### end Alembic commands ###
